### ISSUE TITLE
Swiping does not work when positioning agile-action with absolute

### ISSUE THREAD

**Issue by Serhansolo** [lukaszflorczak/vue-agile#102]
title is self explanatory I supose.

when using following CSS:

`
.agile__actions {
  position: absolute;
  bottom: 0;
  width: 100%;
}
`

the swipe function no longer works.

**Comment by lukaszflorczak** [comment]
Failed to reproduce. Possible reasons: 
1. bug with swiping (resolved in incoming 1.1 version)
2. are you sure your actions don't have 100% height and don't overlay all slide space?
