### ISSUE TITLE
Carousel not working as expected with dynamic slides

### ISSUE THREAD

**Issue by NeoTianHow** [lukaszflorczak/vue-agile#103]
Hi, I've successfully rendered the slides using v-for. However, there is an issue. The thumbnails will not be automatically rendered to the main slide. This issue only occurs with dynamic slide. Below are my codes: 

Update: I managed to get this to work by calling this.$nextTick() after I set the boolean  isSlideLoaded to true.

```
`  <div class="col-lg-6 mb-5 ftco-animate">
          <agile
            v-if="isSlideLoaded"
            class="main"
            ref="main"
            :options="options1"
            :as-nav-for="asNavFor1"
          >
            <div
              class="slide"
              v-for="(slide, index) in slides"
              :key="index"
              :class="`slide--${index}`"
            >
              <img :src="slide" />
            </div>
          </agile>

          <agile
            v-if="isSlideLoaded"
            class="thumbnails"
            id="single-thumbnail"
            ref="thumbnails"
            :options="options2"
            :as-nav-for="asNavFor2"
          >
            <div
              class="slide slide--thumbnail"
              v-for="(slide, index) in slides"
              :key="index"
              :class="`slide--${index}`"
              @click="$refs.thumbnails.goTo(index)"
            >
              <img :src="slide" />
            </div>

            <template slot="prevButton">
              <i class="fas fa-chevron-left"></i>
            </template>
            <template slot="nextButton">
              <i class="fas fa-chevron-right"></i>
            </template>
          </agile>
        </div>`


`export default {
  data() {
    return {

      asNavFor1: [],
      asNavFor2: [],

      isSlideLoaded: false,

      options1: {
        dots: false,
        fade: true,
        navButtons: false
      },

      options2: {
        autoplay: true,
        centerMode: true,
        dots: false,
        navButtons: false,
        slidesToShow: 3,
        responsive: [
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 3
            }
          },
          {
            breakpoint: 1000,
            settings: {
              navButtons: true
            }
          }
        ]
      },

      slides: []
    };
  },`

`mounted() {
    this.slides.push(
      "https://images.unsplash.com/photo-1453831362806-3d5577f014a4?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1496412705862-e0088f16f791?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1472926373053-51b220987527?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );
    this.slides.push(
      "https://images.unsplash.com/photo-1497534547324-0ebb3f052e88?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb&w=1600&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ"
    );

    this.isSlideLoaded = true;

    this.$nextTick(() => {
            this.asNavForMain.push(this.$refs.thumbnails);
            this.asNavForThumbnail.push(this.$refs.main);
          });
  },`
```

**Comment by NeoTianHow** [comment]
Is there anyone that can help me? Is this a library bug?

**Comment by msyagli** [comment]
Yeah, same problem here. It seems it doesn't work with dynamic data or we fail to notice something. My code as well:

`<template>
  <div>
    <agile :arrows="true" :speed="1000" :timing="'linear'" :fade="false" :autoplay="false">
      <div :class="'slide slide--${i}'" v-for="(slide, i) in slides" :key="i">
        <a :href="slide.link">
          <img :src="slide.image" height="100%" width="100%" />
        </a>
      </div>
    </agile>
  </div>
</template>
<script>
import Vue from "vue";
import VueAgile from "vue-agile";
Vue.use(VueAgile);

export default {
  data() {
    return {
      slides: []
    }
  },
  created () {
      this.$http.get("announcement")
      .then(response => {
        this.slides = response.data
      })
      .catch(e => {
        this.$toast.open({
          duration: 3000,
          message: e.response.data.description,
          position: "is-bottom-right",
          type: "is-danger"
        })
      })
  },
  mounted () {
    console.dir(this.slides)
  }
}
</script>
<style>
.agile__nav-button {
  background: transparent;
  border: none;
  color: #fff;
  cursor: pointer;
  font-size: 24px;
  height: 100%;
  position: absolute;
  top: 0;
  transition-duration: 0.3s;
  width: 80px;
}
.agile__nav-button:hover {
  background-color: rgba(0, 0, 0, 0.5);
  opacity: 1;
}
.agile__nav-button--prev {
  left: 0;
}
.agile__nav-button--next {
  right: 0;
}
.agile__dots {
  bottom: 10px;
  left: 50%;
  position: absolute;
  -webkit-transform: translateX(-50%);
  transform: translateX(-50%);
}
.agile__dot {
  margin: 0 10px;
}
.agile__dot button {
  background-color: transparent;
  border: 1px solid #fff;
  border-radius: 50%;
  cursor: pointer;
  display: block;
  height: 10px;
  font-size: 0;
  line-height: 0;
  margin: 0;
  padding: 0;
  transition-duration: 0.3s;
  width: 10px;
}
.agile__dot--current button,
.agile__dot:hover button {
  background-color: #fff;
}

.slide {
  display: block;
  height: 300px;
  -o-object-fit: cover;
  object-fit: cover;
  width: 100%;
}
</style>
`
**Console output:**
`[Vue warn]: Error in callback for watcher "currentSlide": "TypeError: Cannot read property 'classList' of undefined"

found in

---> <Agile> at node_modules/vue-agile/src/Agile.vue
       <AnnounceSlider> at src/components/AnnounceSlider.vue
         <Home> at src/views/Home.vue
           <App> at src/App.vue
             <Root>`

Any help will be appreciated. Thanks.

**Comment by NeoTianHow** [comment]
Hi @msyagli I managed to solve my issue. Please take a look at my updated code.
