### ISSUE TITLE
Dragging to change slide not working on touch device.

### ISSUE THREAD

**Issue by Nesuarg** [lukaszflorczak/vue-agile#104]
I have noticed that the this component does not support dragging on touch devices.

Looking at:
https://github.com/lukaszflorczak/vue-agile/blob/9fe5fb904845f0160ed3c925218adc48e1570227/src/Agile.vue#L144

its seems its always false and never adds the event listener

**Comment by lukaszflorczak** [comment]
Should be fixed in incoming 1.1 version.
