### ISSUE TITLE
Vue warning - "Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors."

### ISSUE THREAD

**Issue by Kovbo** [lukaszflorczak/vue-agile#106]
Hello, please help me to solve the issue with this component.

I'm constantly receiving Vue warning after adding basic carousel code into the main component.

```
<div id="app">
<agile>
  <div>slide 1</div>
  <div>slide 2</div>
</agile>
</div>
```
[Vue warn]: Duplicate presence of slot "default" found in the same render tree - this will likely cause render errors.

found in

---> <Agile> at node_modules/vue-agile/src/Agile.vue
       <Root>

**Comment by Nesuarg** [comment]
Try update vue to latest version, as I remember when having the same issue, it was something with the multiple non named slot, not being supported in older vue versions.

**Comment by Kovbo** [comment]
> Try update vue to latest version, as I remember when having the same issue, it was something with the multiple non named slot, not being supported in older vue versions.

Yeah, you were right! Just updated Vue, and the error disappeared.
Now everything works perfectly, thank you so much!
