### ISSUE TITLE
Prop updates do not change the Agile component's internal settings

### ISSUE THREAD

**Issue by jbrowning** [lukaszflorczak/vue-agile#109]
For example, I have an autoplaying slider and I want to disable the autoplaying functionality programmatically. Simply changing the `:autoplay` prop or an `autoplay` property in the `:options` prop does not update `settings.autoplay` within the component.

**Comment by dedosmedia** [comment]
+1 for this issue

**Comment by divdax** [comment]
Any news?

**Comment by dennisfrijlink** [comment]
I fixed it by using the method "disableAutoPlay()" in the Agile component self. You can trigger it by using "$refs.agile.disableAutoPlay()". If you want to switch you can also use "$refs.agile.toggleAutoPlay()". Not the best way but it works

**Comment by dennisfrijlink** [comment]
`<button @click="$refs.carousel.disableAutoPlay()">click</button>
<agile
  ref="carousel"
  :options="options"
  :navButtons="false"
  :dots="false"
  :autoplay="true"
  :autoplaySpeed="5000"
  :pauseOnHover="false"
  :fade="false"
  :centerMode="false">`
