### ISSUE TITLE
Reset timer after usage goTo method

### ISSUE THREAD

**Issue by thebspin** [lukaszflorczak/vue-agile#110]
Hi i am using the `goTo()` method to go to a certain slide clicking a icon. If i have a transition time of 3500 and i click on a icon after 3000 ms, the slider auto rotates to the next one again just after 500 ms where i expect it to wait another 3500 after i use the method.

**Comment by eduardocmoreno** [comment]
Same here...

**Comment by thebspin** [comment]
> Same here... So I looked inside the Agile.vue code in node modules and I found this method "restartAutoPlay" and it works nice. Just use like this:
> 
> ```
> <button @click="$refs.carousel.next(); $refs.carousel.restartAutoPlay()">next</button>
> ```

That is a really nice find! However it keep stelling me that `restartAutoPlay` is not a function. So i checked using `console.log(this.$refs.carousel)` and there is no `restartAutoPlay` for me to work with. You have any idea why i cant call the function from method or even inline like your example?
