### ISSUE TITLE
Edge not redering text only slides properly

### ISSUE THREAD

**Issue by jackbarham** [lukaszflorczak/vue-agile#113]
I'm using the carousel to display text only testimonials and although it's working fine on Chrome, Firefox and Safari (mobiles are good too) it's not rendering correctly in Edge.

It's currently live so that you can see the issue here, about halfway down: https://www.vibecast.com

I've tried forcing height and also height 100%, but I can't get it to play nicely in Edge.

**Comment by daniellampl** [comment]
i had the same issue in Edge and IE.

i fixed it by setting `flex-shrink` of `agile__slies` to `unset` for those two browser. I tried it on your site and it work (see image)

![image](https://user-images.githubusercontent.com/39054525/67863710-b1afe580-fb24-11e9-8a53-b12b8f303da0.png)

**Comment by jackbarham** [comment]
You legend! I'll give it a try this evening :)

**Comment by daniellampl** [comment]
I created a pull-request --> #124

**Comment by jackbarham** [comment]
Works perfectly :)

**Comment by lukaszflorczak** [comment]
Fixed in incoming 1.1 version.
