### ISSUE TITLE
SlideToSkip is not present

### ISSUE THREAD

**Issue by zeeshanweb-official** [lukaszflorczak/vue-agile#114]
hi there,
i hope you are doing well,
first of all thanks for such a great a gift.
its just gorgeous,
actually i am looking for a functionality that can skip more then one item in the carousel.
like SlidesToShow which is a number.
and there should be a SlidesToSkip as well so that we can skip more then one slides at a time.
thanks.

**Comment by lukaszflorczak** [comment]
Hey. Sorry for a long time without an answer. Could you explain it? Where is the difference between `initialSlide`?
