### ISSUE TITLE
Project is not transpiled!

### ISSUE THREAD

**Issue by jjavuejj** [lukaszflorczak/vue-agile#116]
I like this project. But the problem is, it's not transpiled. If you need to support IE11 or iOS9, using this project will cause errors. This caused me some frustration and a couple hours of lost time thinking it was something that I was doing wrong in my babel or webpack config, only to finally find that it was this project causing the issue.

I tried manually transpiling it only for it to throw errors in my build, so I had go with another option.

Any proper project should be transpiled. It's my fault for not checking before implementing it. Word to the wise, don't get caught in a wild goose chase like me if you need to support any older browsers.

**Comment by thebspin** [comment]
Just found out this  specific plugin is causing my entire project not to run on ie11.. really wish it would be properly transpiled!

**Comment by thebspin** [comment]
I fixed it by letting nuxt transpile it during build

**Comment by teamupdivision** [comment]
We also transpiled the plugin and it works

`build: {
    /*
     ** You can extend webpack config here
     */
    transpile: ['vue-agile']
  }`

**Comment by focussing** [comment]
@teamupdivision in what file do you put this setting?

**Comment by focussing** [comment]
@lukaszflorczak Could you fix this issue easily?

**Comment by daniellampl** [comment]
@focussing you append this settings in you nuxt.config.js

**Comment by focussing** [comment]
Thanks @daniellampl , however I am not using nuxt, but the "normal" Vue-CLI 3.
Besides that; shouldn't this be fixed in this project? Then everybody would be happy :)

**Comment by Rocksride** [comment]
> We also transpiled the plugin and it works
> 
> ```js
> build: {
>     /*
>      ** You can extend webpack config here
>      */
>     transpile: ['vue-agile']
>   }
> ```

thanks a lot, worked for me

**Comment by focussing** [comment]
Hi @lukaszflorczak is this fixed in your latest release? (pls see my previous comment)

**Comment by lukaszflorczak** [comment]
I thought so, but as I delved into it again, I'm not sure if I understand the problem correctly.

I wanted to build next bundles with `--modern` param and this configuration in `babel.config.js`:

```js
presets: [
    [
        '@vue/app',
        {
            useBuiltIns: false,
            targets: {
                ie: '11'
            }
        }
    ]
]
```

and `vue.config.js`:

```js
publicPath: '/vue-agile/',
configureWebpack: {
    output: {
        libraryExport: 'default'
    }
}
```

**Comment by lukaszflorczak** [comment]
@focussing Do you have any suggestions for that?

**Comment by focussing** [comment]
This is the first package that I use which (seems to) need extra settings to get it work. I was triggered with the initial post in this issue, because I do need IE11 support (still being used in 80% of systems in educational institutions in NL.
That is why I asked my question; so regarding your new release, do I need to do something extra or does it work for IE11 out of the box?

**Comment by lukaszflorczak** [comment]
Do you add vue-agile as a dependence by npm/yarn to your project? If yes, please try to use a version from `dev/v1.1.0` branch. 

```yarn add https://github.com/lukaszflorczak/vue-agile.git/#dev/v1.1.0```

**Comment by focussing** [comment]
I would use the latest version via NPM as dependency.
But until now I haven't used it yet; I first want to be sure whether is supports IE11 on forehand.
And because of this issue I was triggered.

**Comment by lukaszflorczak** [comment]
Ok, I tested the coming `1.1.0` version on IE11 (UMD bundle and SPA built with vue-agile installed by npm/yarn) – there should be any problem on this browser.
