### ISSUE TITLE
Swiping Broken on iOS

### ISSUE THREAD

**Issue by nVitius** [lukaszflorczak/vue-agile#117]
Swiping between slides is broken on iOS 12 Safari. I haven't been able to test any older versions or iOS 13 yet, but the issue is easily reproducible on the demo page. The first and second demos cannot be swiped on iOS but the buttons do work. It is interesting to note that the fourth demo with the fade transition between slides does work fine. Also I noticed that after swiping on the fourth demo the first two start working.
I was able to replicate this issue on an app that I am working on.

**Comment by TimonLukas** [comment]
Can confirm - same thing happening for me.

**Comment by fenglinzeng** [comment]
Can confirm - same thing happening for me.

**Comment by TimonLukas** [comment]
I was able to fix this (see PR #121). I have NO idea why this fixes it, but it does.

**Comment by ruchitabavishi** [comment]
I am facing the same issue (swipe is breaking on ios), and I tried to use PR#121 but in that case, images are not displaying in any of the phone (android/ios), can someone help me on this.

**Comment by lukaszflorczak** [comment]
Fixed in incoming 1.1 version.
