### ISSUE TITLE
[Feature Request] disable autoplay on interaction

### ISSUE THREAD

**Issue by Miaoxingren** [lukaszflorczak/vue-agile#120]
disableOnInteraction
Set to false and autoplay will not be disabled after user interactions (swipes)

**Comment by daniellampl** [comment]
The current behavior of autoplay is, that if you are `mouseover` on the agile slide the autoplay function will pause. After leaving the slide the autoplay function will resume.

What exactly do you mean with your feature request?

**Comment by Miaoxingren** [comment]
disable autoplay after user manually slide to next page.

**Comment by lukaszflorczak** [comment]
Just mix `disableAutoPlay` method with `after-change` event.
