### ISSUE TITLE
Is it possible to show a part of next slide?

### ISSUE THREAD

**Issue by michalowskil** [lukaszflorczak/vue-agile#122]
Is it possible to show a part of next slide? Like on this picture:

https://www.jqueryscript.net//images/Easy-Responsive-jQuery-Carousel-Slider-Plugin-FilmRoll.jpg

I have checked :slidesToShow = "1.3" but it doesn't work as I would like.

**Comment by Tes3awy** [comment]
Were you able to solve this issue? If so can you please share the solution with me? Thank you

**Comment by michalowskil** [comment]
I couldn't solve this issue:(

**Comment by mateo2181** [comment]
@michalowskil I did it with CSS:

```
<agile
        :navButtons="false"
        :autoplay="true"
        :infinite="true"
        :speed="700"
        :slidesToShow="2"
        class="my-slider">

       <div> </div> // Slide 1
       <div> </div> // Slide 2
</agile>
```
and in your css file:

```
.my-slider.agile {
    transform: translateX(-25%);
    overflow: visible;
}

.my-slider .agile__list {
    overflow: visible;
}

@media(max-width: 600px) {
    .my-slider .agile__list {
        overflow: visible;
        transform: scale(1.2) translateX(-3%);
    }
}
```

**Comment by lukaszflorczak** [comment]
As mentioned, It's possible with CSS, and it'll be also possible with new `centerPadding` , but it's not ready yet.

**Comment by Asingerdev** [comment]
Hey, just checking in here to see if the `centerPadding` is ready. I'm trying to show part of the next slide as well and having trouble doing it with pure css (when I use `transform: translateX(-25%);` it increases the overall width of the slider). Should look along these lines, just need it for mobile:

<img width="389" alt="Screen Shot 2021-12-13 at 11 44 12 AM" src="https://user-images.githubusercontent.com/45954238/145877777-e789e80d-be41-4c2f-a10b-ef5927494c3f.png">


```
<agile
      :dots="false"
      :infinite="false"
      :nav-buttons="false"
      :slides-to-show="2"
      class="agile-slider"
    >
      <div> </div>
    </agile>
```

**Comment by lukaszflorczak** [comment]
@Asingerdev I can try to help you, but you must share your code for example on codepen. Btw. probably you should add some extra container(s) and set transform for them and not directly for carousel.

**Comment by Asingerdev** [comment]
Thank you @lukaszflorczak. Maybe you could just point me in the right direction. Here's a CodePen with the code and it looks close, just need it to look like the bottom pic as opposed to the top. Maybe adding extra containers like you're saying will help. https://codepen.io/weddingsinger11/pen/RwLyzaV

<img width="507" alt="Screen Shot 2022-01-04 at 11 30 18 AM" src="https://user-images.githubusercontent.com/45954238/148113697-1bd85441-fed4-4ae0-9c91-408fad4a5e3e.png">
<img width="417" alt="Screen Shot 2022-01-04 at 11 32 34 AM" src="https://user-images.githubusercontent.com/45954238/148113713-c6224c89-f368-4e8b-a5ae-b00ee3c45eeb.png">
