### ISSUE TITLE
Center mode not working

### ISSUE THREAD

**Issue by bahung1221** [lukaszflorczak/vue-agile#125]
Thank you for your awesome carousel, 
In my case, everything work great except center mode, when i add `center-mode="true"`, it doesn't change anything, below is my code:

```html
      <div class="searchresult-map__slider">
          <client-only>
            <agile
              :slides-to-show="2"
              :center-mode="true">
              <div
                v-for="(result, index) in results"
                :key="index"
                class="slide">
                <ResultBlock
                  has-title
                  :data="result"/>
              </div>
            </agile>
          </client-only>
        </div>
```

Thanks you in advance 😄

**Comment by azhdarshirinzada** [comment]
any updates?

**Comment by bahung1221** [comment]
> any updates?

It seem this project has not maintained 😄

**Comment by lukaszflorczak** [comment]
Sorry for long answer time. What effect do you expect with an even number of slides? Check it with odd.

**Comment by bahung1221** [comment]
It seems that is my mistake, I will test it again later.

Thank you very much!
