### ISSUE TITLE
Can't resolve image url

### ISSUE THREAD

**Issue by starcraft0429** [lukaszflorczak/vue-agile#127]
When I use local image I can't resolve image. maybe webpack issue???
```
                     <agile :navButtons="false">
                        <div v-for="(sliderItem, index) in sliderList" :key="index" class="slide">
                            <img :src="sliderItem.src" alt="">
                        </div>
                    </agile>
```

when I inspect chrome devtool elements, it didn't resolved
here is screenshot
http://prntscr.com/pvz28h

**Comment by lukaszflorczak** [comment]
Probably this can be helpful: https://stackoverflow.com/questions/37645243/static-image-src-in-vue-js-template
