### ISSUE TITLE
asNavFor not working with dynamic content

### ISSUE THREAD

**Issue by Tes3awy** [lukaszflorczak/vue-agile#128]
Hello there,

I am trying to use the plugin with thumbnails as the navigation for the slider like in demo 4. The only difference is that the images are dynamic. Using the `v-for` doesn't make the sliders in sync. Why is this happening? Is that a bug?.

Please if you have any solution for this let me know. I'd really appreciate it if you answer me very soon.

Thank you :)

**Comment by jorn1** [comment]
I've got the same problem. I really like this carousel but this problem keeps me from using it in my project.

Does anyone have a way to get around the issue? Is there any way to use this carousel with dynamic images?

Thanks.

**Comment by lukaszflorczak** [comment]
Do you use the `reload` method after the change? See the example from this issue: https://github.com/lukaszflorczak/vue-agile/issues/99
