### ISSUE TITLE
Next button should be disable ?

### ISSUE THREAD

**Issue by khom-outsourcify** [lukaszflorczak/vue-agile#129]
Could you check this behavior about next button please ?
The button should not enabled for this, I think.
Because I just set slidesToShow 6 and slide item have 6 items.

I just setting normal setting for slider
codepen: https://codepen.io/khom-outsourcify/pen/dyyxxVG

```
<div v-bind="options">
      <div class="slide" v-for="(item, index) in slide">
           <h3>slide {{ index + 1 }}</h3>
      </div>
</div>
```

```
slide: [1, 2, 3, 4, 5, 6],
options: {
        dots: false,
        slidesToShow: 6,
        navButtons: true,
        infinite: false
}
```

**Comment by lukaszflorczak** [comment]
I fixed this in a little other way:

![Nagranie z ekranu 2020-04-18 o 10 50 02](https://user-images.githubusercontent.com/1818979/79632959-d2b3d380-8162-11ea-864b-3917177e3c71.gif)
