### ISSUE TITLE
Swipe broken in crome

### ISSUE THREAD

**Issue by DRBragg** [lukaszflorczak/vue-agile#131]
Swiping is functional when running in development but Chrome logs the following error: 

`Unable to preventDefault inside passive event listener due to target being treated as passive.`

In production swiping is completely broken.

**Comment by JonBaron78** [comment]
We seem to have the same issue.

> Unable to preventDefault inside passive event listener invocation.
handleMouseDown @ handlers.js?e07f:8

Swiping works but produces (a lot) of error messages in console.

**Comment by Gazouly** [comment]
I have the same issue too, any solutions?

**Comment by d4mn** [comment]
It seems it needs a fix with third parameter being {passive:false} for disableScroll function

**Comment by lukaszflorczak** [comment]
Fixed in `v1.1.0`
