### ISSUE TITLE
Can't scroll the page when touching the slider on Browser

### ISSUE THREAD

**Issue by daohuy34** [lukaszflorczak/vue-agile#132]
Hello !

I have an issue on my project (the same behavior occurs on your demo page) : when trying to swipe down/up the page, if the slider is touched it prevent the page from scrolling. And I am at 1.0.11

Any idea on how to fix this ?

Thank you for your work !

**Comment by lukaszflorczak** [comment]
Should be fixed in incoming 1.1 version.
