### ISSUE TITLE
Slot request

### ISSUE THREAD

**Issue by davestewart** [lukaszflorczak/vue-agile#144]
It would be great to have another slot right below the slides for a caption!

Right now I have to put the caption below the entire unit:

![image](https://user-images.githubusercontent.com/132681/77762949-3b130780-7032-11ea-9006-bac97a90ae1c.png)

Great lib by the way! It just works the way you would expect it to.

**Comment by lukaszflorczak** [comment]
Thanks :) I'm not sure it's a good option. You can always use the next carousel with `asNavFor` option.

**Comment by davestewart** [comment]
Hi, thanks for the reply.

I looked at the prop and [the demo with the thumbnails](https://codepen.io/lukaszflorczak/pen/yrQyBj)... but I don't think you understand what I'm trying to do.

What I meant was - a new slot right below the image would allow the user to have a fixed caption area - this is common on many carousels:

![image](https://user-images.githubusercontent.com/132681/79513149-0a276080-803b-11ea-9ba3-8579aae84180.png)

So in the template, this:

```vue
</div>

<slot name="caption"></slot>

<div class="agile__actions"...
```

Then by hooking into events you could update the static caption.

This is the demo running with the caption *beneath* the navigation.

Does that make it clearer?

**Comment by davestewart** [comment]
I just forked and ran locally.

Here it is working:

![screen capture](http://g.recordit.co/568VTP1evg.gif)

I'll PR it.

**Comment by lukaszflorczak** [comment]
Thank you for the explanation. Generally, it's still possible to do without the slot – the only CSS, but as you said it can be useful for galleries, etc. I decided to add your feature in `v1.1.0`

**Comment by davestewart** [comment]
That's great! Thank you very much 😃 

I see you have a 1.1 roadmap. What's the timescale for an NPM release?

**Comment by lukaszflorczak** [comment]
Today I've finished two main functionalities - better SSR support and dynamically options. Now I have to test changes. Then there are some small issues to fix and also I would like to test  the component on IE11 (there are a few users who expect support for this version)

**Comment by davestewart** [comment]
Nice one. Good luck with the work!
