### ISSUE TITLE
Autoplay is not working until mouse is over the slider

### ISSUE THREAD

**Issue by mikesvis** [lukaszflorczak/vue-agile#154]
**Describe the bug**
Autoplay is not starting until mouse is over the slider (until 1st mouse over). However if change value isAutoplayPaused:false -> true -> false in Vue tools - it unfreezes (

**Expected behavior**
It must autoplay from being mounted, from the very beginning. 

**Environment:**
 - OS: Debian 10
 - Browser Chrome
 - Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by lukaszflorczak** [comment]
Thank you for the issue. To be sure: do you have `pauseOnHover` prop sets on `false` or `true`?

**Comment by cimpok** [comment]
Hi, I have the same issue: autoplay not working since version 1.1.0  if pauseOnHover is set to false. Works OK if pauseOnHover is true.

**Comment by lukaszflorczak** [comment]
I think I fixed it, but I'll publish a fixed version tommorow at the morning. But If you want you can check the version from branch `issue-154-Autoplay_is_not_working_until_mouse_is_over_the_slider` (it'll be very helpful):

```yarn add https://github.com/lukaszflorczak/vue-agile.git/#issue-154-Autoplay_is_not_working_until_mouse_is_over_the_slider```

**Comment by cimpok** [comment]
Autoplay in version 1.1.1 works OK. With any setting of pauseOnHover with untouched slider. Thanks

**Comment by lukaszflorczak** [comment]
Thank you very much for your feedback and I'm sorry for the bug.

**Comment by mikesvis** [comment]
Thank YOU for instant support! Great work! BTW awesome BEM in styles of examples!!!

**Comment by lukaszflorczak** [comment]
Thank you too 😉
