### ISSUE TITLE
Ghost image of dragged element is shown when swiping

### ISSUE THREAD

**Issue by cimpok** [lukaszflorczak/vue-agile#156]
Since version 1.1.0 when swiping the slider left/right (invoking a manual step) a ghost image of the dragged element is shown. Would be prettier if it would be hidden as earlier.
Tested only on desktop (with mouse), not on a touch device. Strangely I observe this only in  Chrome (and derivatives) but not in Firefox.

**Comment by lukaszflorczak** [comment]
Are you able to take a screenshot or record a screen?

**Comment by lukaszflorczak** [comment]
Ah... I understand and I know why. It's because version 1.1 changed the way of how mouse events are detected (before for example form elements was not clickable). I think I will able to fix it by adding `pointer-events: none` for slides during swiping.
