### ISSUE TITLE
Incorrect slide sizing on load, using two carousels

### ISSUE THREAD

**Issue by justindantzer** [lukaszflorczak/vue-agile#159]
**Describe the problem**
I'm using two related carousels similar to https://codepen.io/lukaszflorczak/pen/yrQyBj

On load, the smaller/secondary carousel loads at a much larger size than expected, seemingly at the full container width instead of a width based on slide count.

I assume I'm missing a simple detail, but it is escaping me at present.

**Code**
I attempted to get the gist of what I'm doing in my project here:
https://codepen.io/justin-RB/pen/BaopNKW

I am not currently setting the height of the thumbnail slides, but upon adding the following, the problem persists.
```css
.slide--thumbnail {
  height: 100px;
}
```

**Expected behavior**
Slides to load at the appropriate size.

**Screenshots**
![ezgif-3-4bd1f4e9dc1d](https://user-images.githubusercontent.com/2125752/80010034-d368a480-8497-11ea-9867-41363cdd876d.gif)

**Additional context**
Can confirm the same result in Chrome, Safari, Firefox (at least on MacOS 10.15)

**Comment by lukaszflorczak** [comment]
If you load your slides dynamically, try to use: `:key="slides.length"` for the second carousel. Then probably you'll not need the watcher with reload method.

**Comment by justindantzer** [comment]
Adding the `:key` and removing the water, I get this:
<img width="639" alt="Screen Shot 2020-04-22 at 2 23 41 PM" src="https://user-images.githubusercontent.com/2125752/80019084-fbaad000-84a4-11ea-871f-8295adb34911.png">

**Comment by lukaszflorczak** [comment]
Are you sure you added a `key` param to `agile`? Check this: https://codepen.io/lukaszflorczak/pen/WNQRrbb

**Comment by justindantzer** [comment]
I had actually only added it to the second carousel, but adding it to both makes them load at the appropriate sizes.

However, when adding to both, the carousels no longer behave as nav for the other. I note this in both CodePen examples.

**Comment by lukaszflorczak** [comment]
Right. In this case, if you reload (by method or key) you have to update asNavFor refs. So I propose something like that – the key to refresh carousels and asNavFor update in watcher:
https://codepen.io/lukaszflorczak/pen/WNQRrbb?editors=0011

**Comment by justindantzer** [comment]
That indeed fixed my problem. Thanks so much for your help!

**Comment by lukaszflorczak** [comment]
Thank you very much for ☕️☕️☕️☕️☕️☕️ 
I really appreciate that 😊
