### ISSUE TITLE
Slider sesitivity on mobile devices.

### ISSUE THREAD

**Issue by Wachu91** [lukaszflorczak/vue-agile#16]
It would be great if you could make it less sensitive on mobile devices. At this point it's easy to change slides by mistake. For example, when you're scrolling a page and touch slider area it's almost sure that it will move. 
The solution may be to increase number of pixels you need to move to change slide.

Except that it works great. 
Thanks for this wonderful component!

**Comment by lukaszflorczak** [comment]
Thank you for your issue. In one of the closest versions I'll try to lock a page scrolling while swiping slides and lock carousel while scrolling the page. 

Try also the latest version (`0.2.1`) – I increased minimal swipe distance from 30 to 50 pixels.

**Comment by lukaszflorczak** [comment]
@Wachu91 Could you test version `0.2.2-beta.1`?
