### ISSUE TITLE
Not Center Aligning & uneven spacing on sides. | Vuetify (v-img)

### ISSUE THREAD

**Issue by seamive** [lukaszflorczak/vue-agile#171]
**Describe the bug**
I'm trying to align 6 slide items as the center so they equally distribute space and width but for some reason, it doesn't. I even searched the issues but didn't found a fix, it's probably a bug. It doesn't leave padding/margin in beginning on **LEFT** side and adds extra padding/margin on **RIGHT** side which it shouldn't.

**Code**
```
featuredSliderOptions: {
      autoplay: true,
      centerMode: true,
      dots: false,
      infinite: true,
      navButtons: false,
      slidesToShow: 1,
      responsive: [
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
          }
        },
        {
          breakpoint: 900,
          settings: {
            slidesToShow: 6,
          }
        },
        
      ],
    },
```
```
            <agile :options="featuredSliderOptions">
             @foreach ($app->images as $img)
              <!-- Item -->
              <div class="slide">
                <v-img src="{{ asset($img->url) }}" :max-width="isMobile() ? '80vw' : '145px'" min-height="2vh">
                  <div class="fill-height"></div>
                </v-img>
              </div>
              @endforeach
            </agile>

```

**To Reproduce**
As shown in the image. No margin on left, but there is a margin on right. Even when dragging, it doesn't center using any class or anything. Tried using `text-align: center` and `margin: 0 auto;`

**Expected behavior**
It should center align in the div width and distribute the images evenly with proper spacing from both the left and right sides.

**Screenshots**
URL: [https://prnt.sc/sm2u08](https://prnt.sc/sm2u08)
![image](https://user-images.githubusercontent.com/2825887/82715582-6d975480-9cb1-11ea-9b99-fc1c232189b8.png)

**Environment:**
 - OS: Windows 10
 - Browser Chrome
 - Version: 1.1.3

**Additional context**
Let's hope it can be quickly fixed?

**Comment by lukaszflorczak** [comment]
Could you add CodePen or some additional screenshots to show:
* container size
* single slide size
* img size

**Comment by seamive** [comment]
CodePen: https://codepen.io/seamive/pen/VwvJpJd

**Comment by lukaszflorczak** [comment]
In my opinion, it's not a problem of component – just CSS. 

Is it an effect you expect?

<img width="1318" alt="Zrzut ekranu 2020-05-30 o 09 15 03" src="https://user-images.githubusercontent.com/1818979/83322244-54187e80-a256-11ea-813f-029c9f8db312.png">

If yes, just add:

```css
.slide {
  display: flex;
  justify-content: center;
}
```

**Comment by seamive** [comment]
Why doesn't it automatically align when used `centerMode` and then we have to add additional CSS?

**Comment by lukaszflorczak** [comment]
`centerMode` doesnt change styles of your slide. This option means that if you have `slidesToShow > 1`, the active slide is in the middle (instead in the beginning)
