### ISSUE TITLE
using in Vue3 - works OK - with some console warnings though

### ISSUE THREAD

**Issue by cimpok** [lukaszflorczak/vue-agile#185]
I tested the component under Vue3 (rc.2) - good news it worked for the first try with no modification in my Vue2 code.
However I see the following two warnings in the console each time when moving the slider:
```
[Vue warn]: Component emitted event "beforeChange" but it is neither declared in the emits option nor as an "onBeforeChange" prop.
[Vue warn]: Component emitted event "afterChange" but it is neither declared in the emits option nor as an "onAfterChange" prop.
```
Could you please look at this small issue, so it will be fully suited to Vue3 usage. Thank you.

**Comment by KaKi87** [comment]
Hello, I'm experiencing the same issue. Thanks

**Comment by lukaszflorczak** [comment]
The version for Vue 3 is finally released: https://github.com/lukaszflorczak/vue-agile/releases/tag/v2.0.0
