### ISSUE TITLE
Responsive breakpoints & settings

### ISSUE THREAD

**Issue by lukaszflorczak** [lukaszflorczak/vue-agile#22]
Hi everyone!

I just published `0.3.0-alpha.1` version with support for `options` (all settings in one object), `responsive` and `mobileFirst` attributes. 

You can find descriptions of available options and responsive example [here](https://github.com/lukaszflorczak/vue-agile/tree/develop).

Because responsive support is a very important step for further functionality (like `slidesToShow` etc.) It would be great if someone would like to test it out and share a feedback.

---

To install dev version use a command: 
```
yarn add vue-agile@dev
```

**Comment by bph** [comment]
Would love to try it out. New to vuejs, though. 
Get "Uncaught SyntaxError: Unexpected token import" when trying to use it on single page html

import VueAgile from 'vue-agile'
var app = new Vue({
el: '#vue-app'

The full page is visible here: https://nptp.us/2gAmeqK
});

**Comment by lukaszflorczak** [comment]
To use `import` and other ES6 features you have to use for example [webpack vue template](https://github.com/vuejs-templates/webpack). 

In your case you should use this code:
``` js
Vue.use(window['vue-agile'].default)

var app = new Vue({
    el: '#vue-app'
});
```

In addition, `<agile>` is outside of `<div id="vue-app">`. Finally, you will probably need to use a newer version of vue. My component may not work with version `2.1.*`.

Regards!

---

PS. it's offtopic, so in the future please open a new issue.

**Comment by bph** [comment]
Thank You! And sorry for OT!
