### ISSUE TITLE
Uncaught TypeError: this.$refs.list is undefined

### ISSUE THREAD

**Issue by jzhang28** [lukaszflorczak/vue-agile#229]
Following this sample code, when change the window size, got below error, 

Uncaught TypeError: this.$refs.list is undefined
    getWidth helpers.js:15
    Lodash 5
    mounted Agile.vue:202

VueJs 2.6.14

**Comment by Voskresenskyi-Serhii** [comment]
I have similar problem 

`Uncaught TypeError: Cannot read properties of undefined (reading 'clientWidth') at VueComponent.getWidth (helpers.js?c3e4:15:1)`

Problem hidden in mixin helpers.js
Line 15: `this.widthContainer = this.$refs.list.clientWidth`

An the point, the error occurs, after routing, to a page where not any slider component.
In my case, Im solve problem as call destroy function before my parent component wrapper be destroyed

```
beforeDestroy() {
  this.$children[0].destroy()
},
```
