### ISSUE TITLE
Don't work on RTL websites

### ISSUE THREAD

**Issue by Raze2** [lukaszflorczak/vue-agile#247]
agile show a white page instead of the slider when working on RTL website even if I made rtl parameter true

![image](https://user-images.githubusercontent.com/19956274/183513872-6e1f019e-e54e-4371-bc82-00c4ec69e356.png)
![image](https://user-images.githubusercontent.com/19956274/183513986-09394a7b-1070-4fec-9f5f-fafef6a0974e.png)

**Comment by AlanRow** [comment]
I have same issue, can you please describe why it's closed?

**Comment by Raze2** [comment]
@AlanRow try add this css 

.agile__track {
    direction: ltr;
}

.agile__track * {
    direction: rtl;
}

**Comment by AlanRow** [comment]
@Raze2 Yes, it works. Thank you!

UPD: I had another issue with this solution - slides order was reversed, but I fix it by checking is site RTL and use only first rule in this case (and none otherwise)
