### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by camilosw** [lukaszflorczak/vue-agile#26]
Hi,

Could you add the ability to emit some events? I need to detect when the user move between slides and get the slide number.

Thanks

**Comment by lukaszflorczak** [comment]
OK, this is definitely useful. I'll try.

**Comment by bringmethecode** [comment]
Yes please! it would be really useful to have some callbacks like Slick's afterChange and beforeChange, that way we can have more control over current slide :)

**Comment by lukaszflorczak** [comment]
@camilosw, @bringmethecode, @FrontEndStudio: check this post, please: https://github.com/lukaszflorczak/vue-agile/issues/42
