### ISSUE TITLE
Need example of adding images to the carousel

### ISSUE THREAD

**Issue by lmj0011** [lukaszflorczak/vue-agile#28]
I noticed in the [demo's] code snippets, it's not shown how the images are being included in the slides.

They just seem to "magically" appear.

[demo's]: https://lukaszflorczak.github.io/vue-agile/

**Comment by lukaszflorczak** [comment]
Hey. In the demo code examples I don't show axact slides code because you can put there every html code you want. So, you can set images using for example `style="background-image: url();`, in your CSS or just putting `<img>` inside slides.
