### ISSUE TITLE
Nuxt 1.0.0-rc11 instructions are wrong 

### ISSUE THREAD

**Issue by bovas85** [lukaszflorczak/vue-agile#29]
Everything is correct apart from the plugin declaration.

Apparently it only works with
```
import Vue from 'vue'
import VueAgile from 'vue-agile'

Vue.use(VueAgile)
```

**Comment by lukaszflorczak** [comment]
Thanks, I will check it

**Comment by rlam3** [comment]
Would love insight on how to get this working with NuxtJS. 
The CSS isn't working very well. Is the css independent of vue-agile's own css? 
And is there a better way to compose using data() instead of through CSS?

**Comment by lukaszflorczak** [comment]
There is a minimal amount of CSS that defines the default look of arrows, pagination, sets slides inline, etc. Can you specify what means that...
> The CSS isn't working very well.

**Comment by Carlos-Henreis** [comment]
CSS that defines the default appearance of arrows, pagination (points), defines inline slides, etc. They are not working here on my Nuxt project :*(. Is there any demo about this?

**Comment by lukaszflorczak** [comment]
At the moment no, but I will try to prepare something in the near future. Can you open a new issue and attach a link? Or maybe you could share your project privately to let me test it locally?
