### ISSUE TITLE
Feature - Customizable arrows

### ISSUE THREAD

**Issue by bovas85** [lukaszflorczak/vue-agile#30]
I'd like to put my svg instead of the hardcoded one in the component.

Is there a hacky way to do it for now and would you consider this feature?

**Comment by lukaszflorczak** [comment]
Yes, you can load own arrow content. The option is available, but I forgot to add it to the documentation. 

```
// template part
<agile :arrow="yourArrowCode">

// script part
data () {
    return {
        yourArrowCode: '<svg>...</svg>'
    }
}
```

There are two important things: you should put your SVG/HTML code in one line, without new line chars etc. You probably can't define `:arrow` value in `<template>` part, only as variable in `data()`.

You can also freely change the arrow using CSS.

**Comment by bovas85** [comment]
Sorry one last thing, how do you specify one for left and one for right?

**Comment by lukaszflorczak** [comment]
At this moment no, because in CSS I use `transform: scaleX(-1)` to get mirror reflection. 

``` css
.agile__arrow--prev #arrow-svg {
    transform: scaleX(-1)
}
```

But if you think it would be better to define them separately, I can add this in the next release.

**Comment by bovas85** [comment]
how would I add them outside the wrapper? I'd like them to be midway on the sides so they overflow outside of it

**Comment by lukaszflorczak** [comment]
I'll check it later today. Maybe I will have to slightly improve the structure to make it possible.

**Comment by lukaszflorczak** [comment]
Check `vue-agile@0.2.6`

I removed `arrow` option and added `prevArrow` and `nextArrow`. Now arrows and dots are inside `<div class="agile">`, so you can schange their position easily relative to main Agile container.
