### ISSUE TITLE
Works in development but not in production or after build?

### ISSUE THREAD

**Issue by rlam3** [lukaszflorczak/vue-agile#31]
Works in development during live-reload in NuxtJS but not after you build the project?

Problem: Image becomes stacked upon each other in production whereas the images are inside the carousel. 

I run npm run build and run it on a local heroku cli and it shows slides are stacked upon each other.
In development through live reload, it doesn't have any problems of this sort.

Was wondering if there was some sort of production setting I had to turn on for this to work?

Thanks!

**Comment by rlam3** [comment]
https://github.com/nuxt/nuxt.js/blob/dev/examples/no-ssr/pages/index.vue Had to set no-ssr tags before agile... Maybe it should be included within the agile template?

**Comment by lukaszflorczak** [comment]
I reported it here: 
https://github.com/lukaszflorczak/vue-agile#example-1

`<no-ssr>` tag is specific to nuxt.js only, so i can't add this permanently.
