### ISSUE TITLE
Feature - external arrows / bullet pagination

### ISSUE THREAD

**Issue by bovas85** [lukaszflorczak/vue-agile#32]
At the moment the arrows are only available inside the slider container .
If someone requires the common overlap of arrows with the borders or external bullet navigation it won't allow it as overflow is hidden.

Can you consider adding a way to add these items outside the container like other libraries ?

**Comment by lukaszflorczak** [comment]
I have a plan to add methods like `nextSlide()`, `prevSlide()'. If I'll do this, you will can add actions to any button anywhere.

**Comment by bovas85** [comment]
This is not the events attached but more like a feature to externalise the arrows or bullet navigation.
Indeed events would make it possible but they should be triggered by external buttons rather than from next-prev
