### ISSUE TITLE
Using v-for to populate slides?

### ISSUE THREAD

**Issue by T-Bod** [lukaszflorczak/vue-agile#34]
Is it possible to use a v-for loop on the slide div to dynamically control the number of slides?
Something similar to this?
`        <agile :infinite='false'>
            <div v-for="each_item in list" class="slide slide--1" v-bind:style="{ backgroundImage: each_item.path }"></div>
        </agile>`

**Comment by T-Bod** [comment]
Nevermind, found the answer in a closed issue!

**Comment by lukaszflorczak** [comment]
(The answer)[https://github.com/lukaszflorczak/vue-agile/issues/25].
