### ISSUE TITLE
Vanilla usage

### ISSUE THREAD

**Issue by mpaleo** [lukaszflorczak/vue-agile#35]
Hi
Nice work here!

How can it be used without import/require ?
Example:
https://github.com/hilongjw/vue-lazyload#cdn

Thanks!

**Comment by lukaszflorczak** [comment]
Hey! I'm not sure if it's what you need... but check this question and my response:

https://github.com/lukaszflorczak/vue-agile/issues/22#issuecomment-327034529

**Comment by mpaleo** [comment]
@lukaszflorczak That's exactly what i needed. Thanks !!!
