### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tandasima** [lukaszflorczak/vue-agile#36]
Does this component support the following?
1. Image thumbnails in place of dots.
2. Clicking image for fullscreen view.

Thanks.

**Comment by lukaszflorczak** [comment]
Ad. 1. This is not possible at this time. In the future it will be possible with the `asNavFor` option (like here: [Demos -> Slider Syncing](http://kenwheeler.github.io/slick/))

Ad. 2. No and it is not planned. You can use any external plugin for this. I recommend [Photoswipe](http://photoswipe.com).

**Comment by TitanFighter** [comment]
For the second case I used [Vue-Tinybox](https://github.com/NickKaramoff/vue-tinybox). Implemented within 10 mins.
