### ISSUE TITLE
Slides don't render with v-show

### ISSUE THREAD

**Issue by ianengelbrecht** [lukaszflorczak/vue-agile#37]
It looks like the carousel doesn't render slides correctly if behind a v-show. So:
```
<template>
  <button 
     v-on:click.prevent="toggleShowCarousel">Click to toggle the carousel</button>
   <div  v-show="showCarousel">
      <agile>
        <div class="slide slide--1"><h3>slide 1</h3></div>
        <div class="slide slide--2"><h3>slide 2</h3></div>
        <div class="slide slide--3"><h3>slide 3</h3></div> 
      </agile>
    </div>
</template>
<script>

export default {
 data() {
  return { showCarousel: false }
 },
methods: {
  toggleShowCarousel() {
      this.showCarousel = !this.showCarousel;
    }
  }
}
</script>
```
....

I used the styling for the slides as #1 demo.  <agile v-show="showCarousel">...</agile> has the same behaviour. It seems to work when using a v-if instead of a v-show.

**Comment by lukaszflorczak** [comment]
In v0.3 the initialization of settings will be rebuilt, so the problem should resolve itself. I remember to look at it.

**Comment by lukaszflorczak** [comment]
Hi! Check this: https://github.com/lukaszflorczak/vue-agile#v-if--v-show and the last version.

**Comment by ianengelbrecht** [comment]
Thanks guys, this is great. I'd used a workaround in the interim, but nice
that this is now there.

**Comment by lukaszflorczak** [comment]
I only wonder if leaving this in that form is the best solution and if it is not better to simply call the method inside the component:

``` html
<button @click="toggleCarousel"></button>

<agile v-show="showCarousel" ref="carousel">
    ...
</agile>
```

``` js
toggleCarousel () {
    this.showCarousel = !this.showCarousel

    if (this.showCarousel) {
        this.$refs.carousel.reload()
    }
}
```
