### ISSUE TITLE
Feature: events

### ISSUE THREAD

**Issue by ianengelbrecht** [lukaszflorczak/vue-agile#38]
It would be good to have some events emitted from the carousel, e.g. a 'slide-changed' event could be emitted with the value of the current slide as 
```
this.$emit('slide-changed', this.currentSlide)

**Comment by Accontech-Tigran** [comment]
Can`t wait for this feature:) Thanks in advance

**Comment by lukaszflorczak** [comment]
@ianengelbrecht, @Accontech-Tigran: check this post, please: https://github.com/lukaszflorczak/vue-agile/issues/42
