### ISSUE TITLE
When using v-for inside agile everything is returned stacked together.

### ISSUE THREAD

**Issue by thadino** [lukaszflorczak/vue-agile#39]
Hi,
I love the app as its easy to get into but i cant seem to get my v-for code to work.

When i use the code below i get only 1 dot and i cant use the arrows to change the slide.   
      ```<agile>
        <div v-for="book in books">
          <h3>{{ book.title }}</h3>
        </div>
      </agile>```

![image](https://user-images.githubusercontent.com/14736149/31722387-3d17e070-b41c-11e7-9f58-da688f5b11bd.png)

However, when i use v-for on agile aswell as the div. everything works (though i do get 5 of them).
      `<agile v-for="book in books">
        <div v-for="book in books">
          <h3>{{ book.title }}</h3>
        </div>
      </agile>`

![image](https://user-images.githubusercontent.com/14736149/31722294-03574a9c-b41c-11e7-8e3c-aca46ca6a7e3.png)

Now my question is there anyway to do this without looping through on agile and only on the div? 

Any help is greatly appreciated. thanks :+1: 

full code:
<template>

  <!-- Fullwidth Section -->
  <section class="fullwidth padding-top-75 padding-bottom-70" data-background-color="#f8f8f8" v-if="books">

    <!-- Carousel / Start -->
    <div class="simple-fw-slick-carousel dots-nav">
      <agile>
        <div v-for="book in books">
          <h3>{{ book.title }}</h3>
        </div>
      </agile>
    </div>
    <!-- Carousel / End -->
  </section>
</template>

```
<script>

  import axios from 'axios'
  import Vue from 'vue'
  import VueAgile from 'vue-agile'

  Vue.use(VueAgile)

  export default {
    name: 'listingItems',
    data: function () {
      return {
        Header: '400+ MicroPulses i din lomme',
        Subheader: 'Hvilken bog bliver den næste du lærer?',
        books: []
      }
    },
    beforeCreate () {
      axios.get('http://localhost:3000/api/book')
        .then((resp) => {
          this.books = resp.data
          console.log(resp)
        })
        .catch((err) => {
          console.log(err)
        })
    },

    watch: {
      '$route': 'fetchData'
    },

    methods: {
      set () {
        console.log('run')
        this.showCarousel = true
      }
    }
  }

</script>

<style scoped>

</style>
```

**Comment by tghelere** [comment]
@thadino  I'm having the same problem, how did you fix it?
