### ISSUE TITLE
issue with autoplay

### ISSUE THREAD

**Issue by FranckFreiburger** [lukaszflorczak/vue-agile#40]
Hi,
I noticed that autoplay is not stopped when the component is destroyed. This may lead to some invalid DOM access ( startAutoplay() -> setTimeout() -> nextSlide() -> setSlide() -> this.el.slides[i] may be null).

**Comment by lukaszflorczak** [comment]
Thanks. It should be fixed in `v0.3.0`. There are separate methods to stop/start autoplay. 

<img width="613" alt="zrzut ekranu 2017-10-25 o 10 19 43" src="https://user-images.githubusercontent.com/1818979/31988026-fb4800ec-b96d-11e7-9c82-7edd97866cbc.png">

**Comment by FranckFreiburger** [comment]
thanks !
