### ISSUE TITLE
Events & methods

### ISSUE THREAD

**Issue by lukaszflorczak** [lukaszflorczak/vue-agile#42]
Hi, everyone!

## Events
Version `0.4.0` will receive support for events. At this moment I've added two major events: 
* `beforeChange`
*  `afterChange`. 

The first one returns: `{currentSlide: ..., nextSlide: ...}` when the slide change is initialized, and the second returns: `{currentSlide: ...}` after change (animation time is not taken into account). 

## Methods
I added also methods:
* `goTo(slideNumber)`
* `goToNext()`
* `goToPrev()`
* `getCurrentSlide()` – returns integer

---

Please let me know what other data in events you want to be returned (for example slide change method: autoplay, arrow, dot, swipe) or what other events and methods should I add. Please also explain in few words how the new event, method or returned data could be used – this will make it easier to implement.

---

PS. You can also check [README file from develop branch](https://github.com/lukaszflorczak/vue-agile/blob/develop/README.md#events) for more info and examples.

**Comment by Accontech-Tigran** [comment]
Thank you very much for your efforts! Much appreciated.

**Comment by Accontech-Tigran** [comment]
Sorry   is  there any  approximate date of the release of 0.4 version?

**Comment by lukaszflorczak** [comment]
I can't promise, but there is a chance that next week. You can install dev version (```yarn add vue-agile@dev```). There is some bugs in `slidesToShow` option, but events should work fine.

**Comment by Accontech-Tigran** [comment]
Great news!  Will wait:)

**Comment by Accontech-Tigran** [comment]
I was thinking about onInitialized event. It might be useful. By the way owl carousel has pretty rich API https://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html. It`s a pain to work with it in Vue project because it`s not reactive in its nature.  I hope afterChange event will work nicely for touch and drag events also.

**Comment by wisaninona** [comment]
@lukaszflorczak Thanks for the afterChange event, works well. When will a production version be released? My yarn.lock file isn't liking the 0.4.0 version in tests when resolving:

`error Couldn't find any versions for "vue-agile" that matches "^0.4.0"`

**Comment by stomaskov** [comment]
Any news if and when the new version with events will be released?

**Comment by stomaskov** [comment]
@besrabasant Try changing it to
`<agile ref="homecarousel" :options="options" @after-change="afterChange($event)">
   // SLIDES
</agile>`
i.e. add hyphen

**Comment by besrabasant** [comment]
@stomaskov no success.

**Comment by lukaszflorczak** [comment]
I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features – among other things, better-performing events.
