### ISSUE TITLE
Show more than 1 slide per page

### ISSUE THREAD

**Issue by ItsLhoudini** [lukaszflorczak/vue-agile#46]
Is it possible to set how many slides to show on breakpoint?

**Comment by lukaszflorczak** [comment]
This will be available soon in version  [0.4](https://github.com/lukaszflorczak/vue-agile/projects/4?).

**Comment by chasegiunta** [comment]
Ah! Ran into this today. Wondering if there's been any progress with this. Thanks for your work @lukaszflorczak

**Comment by lukaszflorczak** [comment]
Hey. All the time I'm trying to solve the problem I got and which prevents me from releasing the 0.4 version 😔

**Comment by tecfu** [comment]
@lukaszflorczak Let's talk about that problem so we can get this done :)

**Comment by dmikester1** [comment]
Any updates on this ability?  I was going to use this slider, but without this feature, I have to use something different.

**Comment by austriker27** [comment]
@dmikester1 what did you use instead? I'm trying to find a slider to use in Vue that doesnt require jQuery and allows for multiple slides per page

**Comment by dmikester1** [comment]
We are using vue-carousel for our sliders now.

**Comment by divya2808** [comment]
Was this feature out? What is the prop that we need to pass in for more than one slide?

**Comment by p1n5u** [comment]
@divya2808 As far as I know the fearture is not out yet. But if you need it you can use the code from following pull request/branch which exposes this functionnality:
https://github.com/lukaszflorczak/vue-agile/pull/69

**Comment by lukaszflorczak** [comment]
I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features (like `slidesToShow`, fully breakpoints/responsive support, methods, events, etc.), examples and documentation. I'll be grateful for checking that when the new version is released.
