### ISSUE TITLE
Make this slider SSR compatible

### ISSUE THREAD

**Issue by BorjaRafols** [lukaszflorczak/vue-agile#47]
Currently the are many window.addEventListeners in the code, which makes this code not work in a node environment. Maybe they should all be conditioned so that they do not get applied on the server.

**Comment by lukaszflorczak** [comment]
Check SSR section in documentation. Window events listeners are necessary. In other way how to detect the width of the container, the touc, etc.? It have to be rendered in a browser first. If you had slider and the page would be hosted on php, then after the server side you wouldn't do to much – all real functionality has to be in the browser too. The fact that a node.js based on JS doesn't solve this problem.
