### ISSUE TITLE
Buttons type

### ISSUE THREAD

**Issue by jernejrostan** [lukaszflorczak/vue-agile#50]
Hi,

I think you should add type="button" to <button>

In my case it's treated like submit button and everytime it fires form. It's not that big of an issue for me, but in some cases it could be.

Cheers

**Comment by lukaszflorczak** [comment]
Thank you for reporting – I will fix it in the next update.

PS. I apologize for the long response time, but I have not been available recently.

**Comment by lukaszflorczak** [comment]
Fixed in #53.
