### ISSUE TITLE
v-for reInit issue with vue-slick

### ISSUE THREAD

**Issue by akinhwan** [lukaszflorczak/vue-agile#55]
Hello I am considering using vue-agile instead of vue-slick. I had issues with using v-for to create subcomponents within a Slick component. They were rendered outside of the slick track. 

Would I run into this issue? Any thoughts on comparisons between these two vue carousel libraries?

The following is a reference to the problem I'm describing https://github.com/staskjs/vue-slick/issues/26

Thanks!

**Comment by lukaszflorczak** [comment]
Thank you for your message and I'm sorry for such a long absence. I try to creating vue-agile only in Vue-way, without jQuery. And the component was created from scratch. Only props names and features are inspired by slick. 

By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation. I'll be grateful for checking that when the new version is released.
