### ISSUE TITLE
Slick Methods

### ISSUE THREAD

**Issue by akinhwan** [lukaszflorczak/vue-agile#56]
Are Slick Methods such as slickGoTo, slickAdd, slickRemove supported? Didn't see anything on the demo page in regards to the API for agile

**Comment by lukaszflorczak** [comment]
I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation. And methods like that will be available too.
