### ISSUE TITLE
Can't handle empty passed template

### ISSUE THREAD

**Issue by Cobertos** [lukaszflorczak/vue-agile#57]
Similar to: https://github.com/lukaszflorczak/vue-agile/issues/25

The recommendation is to use `v-if` and `v-show` to hide the component until the inner content is loaded. If this isn't used in an example like the following and items is loaded asynchronously (or is undefined until loaded):

```
<agile>
    <div v-for="item in items">
        <img :src="item.src">
    </div>
</agile>
```

...then the following (similar) error is given:

<img width="783" alt="screen shot 2018-03-13 at 11 30 16 am" src="https://user-images.githubusercontent.com/6759176/37352017-b255a0a8-26b2-11e8-9c30-61e355002d2f.png">

It would be much nicer to not require this `v-if` in `<agile>` as it's one more thing to add and remember. If `vue-agile` can handle this, why not include it as default functionality. `v-for` already acts this way as passing `v-for` an undefined `items` will create no error and no iterations, which is nice, though maybe not expected until fully familiar with Vue. But if Vue is doing it, wouldn't it make more sense to align with the expectations of their ecosystem? Just not sure if it's possible.

**Comment by burakkp** [comment]
Did you have any solution for that error? I have the same problem.

**Comment by burakkp** [comment]
> Similar to: #25
> 
> The recommendation is to use `v-if` and `v-show` to hide the component until the inner content is loaded. If this isn't used in an example like the following and items is loaded asynchronously (or is undefined until loaded):
> 
> ```
> <agile>
>     <div v-for="item in items">
>         <img :src="item.src">
>     </div>
> </agile>
> ```
> ...then the following (similar) error is given:
> 
> <img alt="screen shot 2018-03-13 at 11 30 16 am" width="783" src="https://user-images.githubusercontent.com/6759176/37352017-b255a0a8-26b2-11e8-9c30-61e355002d2f.png">
> 
> It would be much nicer to not require this `v-if` in `<agile>` as it's one more thing to add and remember. If `vue-agile` can handle this, why not include it as default functionality. `v-for` already acts this way as passing `v-for` an undefined `items` will create no error and no iterations, which is nice, though maybe not expected until fully familiar with Vue. But if Vue is doing it, wouldn't it make more sense to align with the expectations of their ecosystem? Just not sure if it's possible.

Did you have any solution for that error? I have the same problem.

**Comment by Cobertos** [comment]
You just have to add a `v-if` on the `<agile>` component so it doesn't
render if the content inside is not ready. This means Vue won't try to
render/create/call the agile component until it has the necessary data it
needs to work.
