### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by kwdtje** [lukaszflorczak/vue-agile#58]
Hi,

Is it possible to use Vue Agile as a standalone component (i.e. as an external script). I'm using a PHP backend with VUE and Bootstrap VUE as external scripts included in head. Can i do the same with Vue Agile? If that's not the case, do you mind share the unminified version of agile js so I can make it standalone? :-)

Thanks in advance.

**Comment by lukaszflorczak** [comment]
I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples. And I'll try to add relevant information to the documentation.
