### ISSUE TITLE
0.4.0 alpha: Styles / Slider broken under Samsung Browser (Android 7 & 8)

### ISSUE THREAD

**Issue by devshack** [lukaszflorczak/vue-agile#61]
Hi,

the "official" 0.3.7 release of the vue agile slider works just fine in the Samsung Browser under Android 7 and 8.

But since 0.4.0 (alpha), it seems to be broken. The slider is completly messed up and has no styling anymore.

Which is bad, I really need the latest methods and events :-D

**Comment by lukaszflorczak** [comment]
I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation. I'll be grateful for checking that when the new version will be released.
