### ISSUE TITLE
Defensive changes we had to make to get 2.8.2 working:

### ISSUE THREAD

**Issue by Meekohi** [lukaszflorczak/vue-agile#62]
I don't know if this will be useful feedback so feel free to close this issue if not!

The current `master` branch is not working for us unfortunately -- we are using VueJS, and tiny-slider is not getting torn down precisely when `.destroy` is called, which is leaving our shadow DOM out of sync with the real DOM and causing problems (at least this is my best diagnosis).

In 2.8.2 everything is pretty much working, with the one exception of controls not having the `hidden` attribute reset correctly, which is easy enough for us to fix manually. I had to make the following three additional changes to get 2.8.2 working for our purposes (I think these all can get called on timers, and if the elements are destroyed before the timer goes off they throw errors):

Sanity check that `el` exists in `isVisible`:
```
function isVisible(el) {
  return el && el.offsetWidth > 0 && el.offsetHeight > 0;
}
```

Sanity check that `el` exists in `resetDuration`:
```
function resetDuration (el, str) {
  if (el && RANSITIONDURATION) { el.style[TRANSITIONDURATION] = str; }
}
```

Sanity check that `container` exists in `doContainerTransform`:
```
function doContainerTransform (val) {
  if (val == null) { val = getContainerTransformValue(); }
  if(container) {
    container.style[transformAttr] = transformPrefix + val + transformPostfix;
  }
}
```

**Comment by lukaszflorczak** [comment]
Thank you for the information. I'll get to know this.

PS. I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation.

**Comment by Meekohi** [comment]
Awesome, looking forward to checking it out. Let me know if you need a second set of eyes on it -- is it going to be a different repo?

**Comment by Meekohi** [comment]
Ah nevermind I see the `dev/v1.0.0` branch now.

**Comment by lukaszflorczak** [comment]
I think the problem could exist because I used `element.cloneNode` for some reasons. In `v1.0` I used additional slots instead so I think the problem shouldn't exist anymore.
