### ISSUE TITLE
Exception on mousedown

### ISSUE THREAD

**Issue by henrikmerlander** [lukaszflorczak/vue-agile#63]
When the mouse is used to switch slides by dragging, this error is logged to the console. The carousel still works as expected, though.

> [Intervention]  Unable to preventDefault inside passive event listener due to target being treated as passive. See \<URL\>

![image](https://user-images.githubusercontent.com/5367666/44469890-b9265580-a628-11e8-95d1-9ac32755b88d.png)

`vue-agile: 0.3.7`
`Google Chrome: Version 68.0.3440.106 (Official Build) (64-bit)`

**Comment by lukaszflorczak** [comment]
Thank you. I'll check it.

PS. I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation.

**Comment by lukaszflorczak** [comment]
Error not confirmed in the upcoming `v1.0`.

**Comment by phongloihong** [comment]
Hi 
After update v1.0.11 i still get this error
