### ISSUE TITLE
component parameters

### ISSUE THREAD

**Issue by PedroRamosRguez** [lukaszflorczak/vue-agile#64]
Hi, im using this awesome component but have a little problem. I'm using this componente by  vue-agile.min.js downloaded from [here](https://www.jsdelivr.com/package/npm/vue-agile). The component works perfectly but if i config a :autoplaySpeed, pauseonHover or other parameter, these parameters its not updated. I dont know if maybe is an issue or im doing something wrong

Thx a lot.

**Comment by danielchodusov** [comment]
@PedroRamosRguez Hey! Did you managed how to get that params updated? I'm having the same issue.

**Comment by PedroRamosRguez** [comment]
HI @danielchodusov  i didnt research a lot but if you change the default value in `autoplaySpeed:{type:Number,default:xxxx}` objetct in ` vue-agile-.min.js` u can change the autoplay speed. I think the problem can be in the function to change dynamicly this value. Dont fix the problem but can be a min solution >.<. Hope can help you ^^

**Comment by lukaszflorczak** [comment]
It probably changed in some version of Vue and now you can't use `camelCase` in props. 

It should works:
```
<agile :auto-speed="1000">
```

PS. I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code, many new features, examples and documentation.
