### ISSUE TITLE
Typescript configuration

### ISSUE THREAD

**Issue by smac89** [lukaszflorczak/vue-agile#71]
For use with Typescript, here is a declaration file `vue-agile.d.ts`:

```ts
declare module 'vue-agile' {
    import Vue, {PluginObject} from 'vue';

    const VueAgile: PluginObject<{}>;
    export default VueAgile;
    export const Agile: Vue;
}
```

**Comment by webfacer** [comment]
@smac89 why you set the this line "export const Agile: Vue". Could you tell me why this line is important to set.
Thanks

**Comment by smac89** [comment]
@webfacer This is just to follow the same standard as the module. Back when I made this module definition file, the author of this library was exporting an object called `Agile` from the module in `index.js`. You can see the history of that file [here](https://github.com/lukaszflorczak/vue-agile/commits/master/src/index.js), and I'm referring to this change here:

https://github.com/lukaszflorczak/vue-agile/commit/7c8eb21b9b13d767571f29582787ff7927386915#diff-1fdf421c05c1140f6d71444ea2b27638

But as you can see that export has actually changed because of this commit:

https://github.com/lukaszflorczak/vue-agile/commit/e5d3ddc2b8aafe4a91ac32ca7a6b458fc4e647dd#diff-1fdf421c05c1140f6d71444ea2b27638

So the above definition should change to:

```typescript
declare module 'vue-agile' {
    import Vue, {PluginObject} from 'vue';

    const VueAgilePlugin: PluginObject<{}>;
    export default VueAgilePlugin;
    export const VueAgile: Vue;
}
```
