### ISSUE TITLE
Pause on hover seems to reset timer?

### ISSUE THREAD

**Issue by nickycdk** [lukaszflorczak/vue-agile#72]
It seems pauseOnHover doesnt work quite as expected... 
I've set the autoplaySpeed to 10 secs, and if I then hover the slider after 5 secs, it should pause, then i mouse out from the slider - After 2 seconds, i hover it again, and then mouse out again.. 
 Then I would expect it to pickup/resume where I left, but it seems like it just restarts the timer, and i have to wait 10 seconds again, when in reality I would expect it to change after ex: 3 seconds, and i did a mouseover after 5 seconds and 2 seconds, so should be 3 seconds left of the interval...

**Comment by lukaszflorczak** [comment]
Thank you. I'll try to fix it.

PS. I'm sorry for such a long absence. By the way, I would like to inform you that I'm finishing work on a new version of vue-agile, which has a completely refactored code and many new features.
