### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by lukaszflorczak** [lukaszflorczak/vue-agile#77]
Prepare component for as good Nuxt.js support as possible.

**Comment by horshechnyk** [comment]
Still waiting)

**Comment by khom-outsourcify** [comment]
Still waiting)

**Comment by pangboww** [comment]
Still waiting)

**Comment by pixelpromis** [comment]
Gogogo!

**Comment by mateo2181** [comment]
This is working?

**Comment by pieer** [comment]
Just need to transpile, right?

**Comment by lukaszflorczak** [comment]
Today I've started working on better support for SSR. I'm close to the final effect. You can check [this branch](https://github.com/lukaszflorczak/vue-agile/tree/dev/ssr-support) for updated docs and the component. I also created repository with working demo: [nuxt-agile](https://github.com/lukaszflorczak/nuxt-agile).
