### ISSUE TITLE
Inconsistant widths

### ISSUE THREAD

**Issue by LtLoafer** [lukaszflorczak/vue-agile#81]
Hi,

I really like this carousel but I am having an issue where upon loading it in the browser it sometimes displays it correctly and sometimes it doesn't and I cannot identify the cause. When correct, the first slide containing just text and the following two image slides are centred perfectly. When incorrect, they do not. 

```   <div class="container">
        <div class="row justify-content-center full-height">
            <div class="col-12 col-md-10">

                    <agile :arrows="true" 
                    :speed="1000" 
                    :timing="'linear'" 
                    :fade="true" 
                    :autoplay="false">


                    <div class="slide">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    </div>

                    <div class="slide">
                        <img src="{{ asset('storage/images/castellain_sized.jpg') }}" alt="" >
                    </div>

                    <div class="slide">
                        <img src="{{ asset('storage/images/Castellain11.jpg') }}" alt="">
                    </div>

                </agile>
            </div>
        </div>
    </div>
```

When working correctly, Chrome shows the `slide div` element style width as 920px, but when incorrect as 1264px. But just reloading will switch between them. Interestingly, flicking on the device toolbar in Chrome tools will always revert it correctly even when reverting back out of device mode.

Also, when incorrect, the `div class="agile__slides agile__slides--regular"` is showing a width of 3792px but 2760px when correct.

My CSS

```
.slide {
  align-items: center;
  display: flex;
  justify-content: center;
  text-align: center;
}

.slide  p {
  color: #805649;
  font-size: 16px;
  font-weight: 300;
  margin-right: 5%;
  margin-left: 5%;
  display: flex;
  text-align: center;
  margin: auto;
}


  .slide img {
    width: 100%;
  }

```

Maybe I doing something incorrectly? Thank you

**Comment by lukaszflorczak** [comment]
Hi. Do you use a `1.0.4` version? I fixed the problem like your in that release.

**Comment by LtLoafer** [comment]
Hi. Yes, I am using version 1.0.4. Thanks

**Comment by lukaszflorczak** [comment]
Ok, I'll check this and let you know

**Comment by LtLoafer** [comment]
```
mounted () {
         
	console.log(this.$refs.list.clientWidth)
```

is either displaying 1264 or 920.

Refreshing the browser will show the values alternating between the two.

**Comment by lukaszflorczak** [comment]
OK... The component watches the window size changes and then carousel size is also checked and updated. The first time that method runs in `mounted()` and `mounted()` is run when should be ready. I tested the component on a very low connection with very big external CSS that overwrote my initial container size and everything worked great. Are you sure that any other script doesn't change container size?

**Comment by LtLoafer** [comment]
Good question..I'll check.

**Comment by LtLoafer** [comment]
How is $refs.list.clientWidth first detected within the code?

**Comment by lukaszflorczak** [comment]
It's initialized by `this.rerender()` method in `mounted()`.

**Comment by LtLoafer** [comment]
Hi, 

I think it might have something to do with Bootstrap 4 affecting the container size, especially since bootstrap is mobile first now. So i'm guessing that bootstrap is changing the container size and it sometime conflicts with the carousel. The most frustrating part is that is not consistently doing it.

**Comment by lukaszflorczak** [comment]
As a temporary fix you can use a timeout and `reload()` method:

```js
setTimeout(() => {
    this.$refs.yourCarousel.reload()
})
```

I will test vue-agile with Bootstrap, but tell me first, what version do you use and how (and where) do you load bootstrap js and css files.

**Comment by LtLoafer** [comment]
Hi Lukasz,

The timeout does solve the issue for now. Thanks

I'm using Bootstrap v4.3.1 within Laravel v5.8.11, hence Bootstrap is used via npm. The JS and CSS is compiled with Laravel mix v4.0.15 (webpack). 

```
<head>
 <script src="{{ asset('js/app.js') }}" defer></script>
 <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>

```

Thanks

**Comment by chemic** [comment]
I have the same issue that image width (what is attached to .slide style) upon load.. resizing the browser window fixes the width to right one. setTimeout > reload kind of hot-fixes it, but it's not nice :)

**Comment by ipa1981** [comment]
It looks the problem is deeper.

From my observation, a similar effect happens when you use `v-show` (or even possible if transitions are used)  higher than `<agile>` in the structure. The component is hidden when it is mounted. Maybe this makes it behave unexpectedly. Could be this the case?

**Comment by lukaszflorczak** [comment]
At the start, component read the width of the container (it's used for calculation track width, etc) and set sliders. That's why I assume that where the carousel is mounted also the parent container is visible and has final width. But in `v1.1.0` the way how the component reacts on props and settings change (all will be more dynamic, based on computed) so I hope that maybe that will be also more useful to situations like that.
