### ISSUE TITLE
prepareSlidesClasses() attempts to add class to elements that don't exist

### ISSUE THREAD

**Issue by DjOli** [lukaszflorczak/vue-agile#83]
Conditions:
* carousel with a number of items
* slidesToShow > 1
* infinite = false
* centerMode = true

Result: 
Essentially an out of bounds exception, but in reality, it can't read classList from undefined.

**Comment by DjOli** [comment]
Some things i've noticed: 
* The start variable is modified when this.centerMode is true. It doesn't take into account this.settings.centerMode, meaning you have to provide the centerMode prop for this if statement to even fire.
* In the case where infinite is false, and centerMode is true, this will fail at the start of the array as the start will be a negative integer.
* In the case where infinite is false and centerMode is true, this will fail at the end of the array as start + this.settings.slidesToShow will be greater than the array length.

The quick and easy solution will be a null check, and given it's simply adding a class, I think this would be fine.

However the fact that it uses the centerMode prop, and not the setting, while easy to work around, may cause confusion to those who don't go digging through the code. I suspect the mixup between props and settings may be in other places in the code, but I haven't looked, the thought just crossed my mind.

**Comment by DjOli** [comment]
Side note: I'm happy to raise the pull request to handle the null check, and look into the centerMode issue more closely, just say the word.

**Comment by lukaszflorczak** [comment]
Hi! Thank you for your issue. Unfortunately, I am without access to a computer to the and of the week, so I can't check it now and fix. Of course, feel free to add pull request. 

PS. Are your slides loaded dynamically? For example from API response? At this case you should use `v-if`.

**Comment by DjOli** [comment]
No worries. The slides are loaded dynamically, and I am using v-if. 

I'll try and get around to raising a pull request for it today.

**Comment by DjOli** [comment]
Raised PR: https://github.com/lukaszflorczak/vue-agile/pull/84

**Comment by lukaszflorczak** [comment]
OK, thanks. I'll check this as soon as possible.
