### ISSUE TITLE
The document scroll remains disabled on iOS after enableScroll()

### ISSUE THREAD

**Issue by yensresmann** [lukaszflorczak/vue-agile#85]
There seems to be an issue with the document scroll on iOS. After touching one of the slides, the page scroll remains disabled.

https://github.com/lukaszflorczak/vue-agile/blob/3039aca5500cfdb6d5e7404e7379b246ad3ec3a0/src/Agile.vue#L579

Changing the enableScroll() function to the following, fixes the issue:

`document.ontouchmove = () => true`

**Comment by lukaszflorczak** [comment]
Of course! Thank you. I fixed it in `v1.0.6`.
