### ISSUE TITLE
iOS - Can't scroll the page when touching the slider

### ISSUE THREAD

**Issue by adrienlamotte** [lukaszflorczak/vue-agile#86]
Hello !

I have an issue on my project (the same behavior occurs on your demo page) : when trying to swipe down/up the page, if the slider is touched it prevent the page from scrolling.

Tested on iOS 10 & 12.

Any idea on how to fix this ?

Thank you for your work !

**Comment by lukaszflorczak** [comment]
Hi. What version do you use? This bug has been fixed in version [1.0.6](https://github.com/lukaszflorczak/vue-agile/releases/tag/v1.0.6).

**Comment by adrienlamotte** [comment]
@lukaszflorczak hum, i'm using the 1.0.7...

Just tried on your codepen (https://codepen.io/lukaszflorczak/pen/EJRNMM), same behavior.

**Comment by lukaszflorczak** [comment]
OK, I'll check this again.

**Comment by lukaszflorczak** [comment]
The problem was a little different. Check `v1.0.8` – should be fine now.

**Comment by adrienlamotte** [comment]
Thank you @lukaszflorczak , it works :-)

**Comment by daohuy34** [comment]
i up ver 1.0.8 but not working, problem is same
