### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by nickycdk** [lukaszflorczak/vue-agile#87]
It doesn't seem to work in IE11 - All demo's are just empty: 
https://lukaszflorczak.github.io/vue-agile/

Any ideas?

**Comment by lukaszflorczak** [comment]
Thanks. I'll check this.

**Comment by lukaszflorczak** [comment]
Hi! Sorry and thank you for a long time of waiting. Unfortunately, I had a problem with access to IE11. 
The bug should be fixed in `1.0.9` version.

**Comment by adrienlamotte** [comment]
@lukaszflorczak IE11 was working fine in the 1.0.9 but seems to be broken in 1.0.10 (error on startup preventing the app to load)

Thanks !

**Comment by lukaszflorczak** [comment]
Hi. Could you copy and paste the error message? And start a new issue please – I think that the error is not related to the situation in this issue.

**Comment by adrienlamotte** [comment]
@lukaszflorczak you're right it's not directly related. I'll create a new issue but I can't do it right now because I downgraded to 1.0.8 for now (and fixed the IE11 issue with the CSS you added in the 1.0.9).

I'll try to update again for the next release of my project.

**Comment by lukaszflorczak** [comment]
OK, thanks. Do you have vue-agile installed by npm/yarn?

**Comment by adrienlamotte** [comment]
I use npm on that project
