### ISSUE TITLE
Resizing method breaks slidesToShow

### ISSUE THREAD

**Issue by remychvn** [lukaszflorczak/vue-agile#90]
If I maximize the window the number of columns displayed is not consistent.

![Peek 2019-05-27 22-35](https://user-images.githubusercontent.com/5863606/58438720-884fe100-80d0-11e9-863b-00699124ca1f.gif)

If I resize the window manually, I obtain the expected behaviour

![expected](https://user-images.githubusercontent.com/5863606/58438750-c5b46e80-80d0-11e9-84a2-ad245d1ca742.gif)

Module options
```
 options: {
        navButtons: true,
        slidesToShow: 3,
        infinite: false,
        initialSlide: 0,
        mobileFirst: true,
        centerMode: false,

        responsive: [
          {
            breakpoint: 100,
            settings: {
              slidesToShow: 1,
              navButtons: false
            }
          },
          {
            breakpoint: 700,
            settings: {
              slidesToShow: 2,
              navButtons: false
            }
          },
          {
            breakpoint: 1250,
            settings: {
              navButtons: true,
              slidesToShow: 3,
              dots: false
            }
          }
        ]
      },
```
Nice work on this component by the way :+1:

**Comment by lukaszflorczak** [comment]
Thanks for your request. Could you show me a result of something like that, please:

```vue
<!-- template -->
<agile :options="options" @breakpoint="currentBreakpoint($event)">
    ...
</agile>
```
```js
// script
methods: {
    currentBreakpoint (event) {
        console.log(event)
    }
}
```

**Comment by remychvn** [comment]
index.js:668 {breakpoint: 700}
index.js:668 {breakpoint: 1250}

In both cases

**Comment by Capati** [comment]
Any solution?

**Comment by lukaszflorczak** [comment]
In `v1.1.0` there will be a throttle on getWidth method when window is resized and settings will be reader dynamically, so it should fix problems like that.
