### ISSUE TITLE
slidesToShow: 1 not working for mobile view

### ISSUE THREAD

**Issue by saerose** [lukaszflorczak/vue-agile#93]
Maybe it's nothing but I'be been struggling with this and I can not comprehend what is happening. I've created a gallery with the component and I have the slides to show set to 1, it works perfectly with web and tablet view but when it comes to mobile it breaks and shows the slides one on top of another or next to the actual slide. 

<img width="197" alt="Captura de pantalla 2019-06-11 a las 15 17 57" src="https://user-images.githubusercontent.com/33838693/59276188-1c3bb400-8c5e-11e9-8b32-79fa6800e9d3.png">

I can also copy my code if needed but I'm not doing anything out of the options given. Any thought of what can be happening?
(As I said it works perfect on other views, it's just the mobile one).

**Comment by lukaszflorczak** [comment]
Hey. I apologize for the long waiting time – I've been inactive for the last 2 weeks.
I'm not sure but it looks like problems with your styles. Could you share a link to your website or maybe create a CodePen demo with the problem?
