### ISSUE TITLE
In rtl mode, swipe direction is wrong

### ISSUE THREAD

**Issue by kimixu717** [lukaszflorczak/vue-agile#95]
https://www.amazon.ae/Ninebot-Segway-ES2-Kick-Scooter/dp/B07MWWQWJS/ref=mp_s_a_1_1?ie=UTF8&language=ar_AE&pd_rd_r=5HZACM2X0G8M8PWGJ2M6&pd_rd_w=dm3xk&pd_rd_wg=xDqqK&pf_rd_i=mobile&pf_rd_m=A2KKU8J8O8784X&pf_rd_p=ce23db49-38d3-46cb-8e86-2e8865cef92c&pf_rd_r=N7VKRBSK3D8FBFFF1KNH&pf_rd_s=blackjack-experiment-1&pf_rd_t=Gateway&qid=1560756864&s=toys&sr=1-1  as a reference, please open in mobile.

**Comment by kimixu717** [comment]
And it should not let users to set the rtl mode, it should be read by the html element's direction attribute

**Comment by lukaszflorczak** [comment]
Hey! Thank you for the issue. I'll try to fix it until the end of the week.
