### ISSUE TITLE
Error syntax on ie 11

### ISSUE THREAD

**Issue by tomosiahoang** [lukaszflorczak/vue-agile#98]
Error: Syntax error (=>):  
`const install = (Vue) => { 
   Vue.component('agile', VueAgile)
}`
in  
> vue-agile/src/index.js

**Comment by MennyMez** [comment]
I have the same issue. Any workaround?

**Comment by khom-outsourcify** [comment]
Same issue.
```
SyntaxError: Syntax error
```

**Comment by tomosiahoang** [comment]
I solved it using polyfill

**Comment by khom-outsourcify** [comment]
> I solved it using polyfill

Which feature that you use from polyfill to solved this issue?

**Comment by dsktschy** [comment]
> I solved it using polyfill

@tomosiahoang I want to know which polyfill solved this.

**Comment by dsktschy** [comment]
I solved with this setting.
```
// nuxt.config.js
build: {
  transpile: ['vue-agile']
}
```

**Comment by SavkaTaras** [comment]
I have the same thing. Does anyone know which version works on IE 11?

Thanks

**Comment by lukaszflorczak** [comment]
I tested the coming `1.1.0` version on IE11 (UMD bundle and SPA built with vue-agile installed by npm/yarn) – there should be any problem on this browser.
