### ISSUE TITLE
Slider content is not dynamic

### ISSUE THREAD

**Issue by sebenik** [lukaszflorczak/vue-agile#99]
I slightly modified the default example so it takes an array and renders slides based on number of items in that array.

I added 2 buttons so you can pop or add elements to that array. By doing so, vue-agile slider is not working as expected.

Is this a bug or not even supported?

Edit: ok it kinda works after calling reload method, but if you try to remove the slide you're currently looking, it jumps back to first slide but it doesn't recognize that, so after clicking next, you jump to first again.

To reproduce: go to last slide, then click 'pop slide', then go to next slide.
https://codepen.io/anon/pen/MMGMxZ

Desired behavior is to slide with animation to previous slide after deleting the current one.

**Comment by comod** [comment]
Even with the Watcher, this bug still exists. After adding Slides, Images appear side-by-side. After "hard" Reload everything is fine.
